### ISSUE TITLE
Update Search Functionality to Accommodate Riot IDs

### ISSUE THREAD

**Issue by CarlVic02** [vkaelin/LeagueStats#80]
#### Description
RiotGames is phasing out "Summoner Names" in favor of Riot IDs (Name#Tag). However, the current search functionality relies on "Summoner Names" for stat retrieval. 

#### Files
- **summonerendpoint.ts**

#### To Reproduce
Please search for a new Summoner after the RiotID transition

#### Tasks
- [ ] Update dependency from **summonerName** to **summonerPUUID** in **summonerendpoint**.
- [ ] Implement a new endpoint, "AccountV1," utilizing [/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}](https://developer.riotgames.com/apis#account-v1/GET_getByRiotId) to obtain the PUUID.
- [ ] Use the acquired PUUID from the AccountV1 endpoint to get **SummonerDTO**.

#### Notes
While I've proposed a solution, I wonder if it's optimal.
I'm eager to update the search functionality, but need guidance and time. I am open to collaboration and feedback as well.

**Comment by vkaelin** [comment]
Thanks for the contribution. You can try to implement it!

Here is the idea I have:

When the user search for a summoner, if his input contains the `#` symbol, call the new endpoint. If it does not, use the old one.  The rest of the code should still remain the same I think.
